edit pull

diff --git a/.github/workflows/tester-pull.yml b/.github/workflows/tester-pull.yml
--- a/.github/workflows/tester-pull.yml
+++ b/.github/workflows/tester-pull.yml
@@ -24,7 +24,9 @@ jobs:
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
       - name: Pull Docker Image
-        run: docker pull gearvian/flask-github-actions:latest
+        run: |
+          echo "Pulling Docker image..."
+          docker pull gearvian/flask-github-actions:latest || echo "Docker pull failed"
 
       - name: Build and Push
         uses: docker/build-push-action@v6
